Description of ToolBlockAudio
Home > ACA-Code > ToolBlockAudio.m
ToolBlockAudio
PURPOSE
blocks audio signal into overlapping blocks
SYNOPSIS
function [x_b, t] = ToolBlockAudio(x, iBlockLength, iHopLength, f_s)
DESCRIPTION
blocks audio signal into overlapping blocks
>
> @param x: audio signal (dimension length x 1)
> @param iBlockLength: target block size
> @param iHopLength: target hopsize
> @param f_s: sample rate
>
> @retval x_b (dimension iNumOfBlocks x iBlockLength)
> @retval t time stamps for blocks
 ======================================================================
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ComputeSpectrogram computes a mel spectrogram from the audio data
FeatureTimeAcfCoeff computes the ACF coefficients of a time domain signal
FeatureTimeMaxAcf computes the ACF maxima of a time domain signal
FeatureTimePeakEnvelope computes two peak envelope measures for a time domain signal
FeatureTimeRms computes the RMS of a time domain signal
FeatureTimeStd computes the standard deviation of a time domain signal
FeatureTimeZeroCrossingRate computes the zero crossing rate from a time domain signal
PitchTimeAcf computes the lag of the autocorrelation function
PitchTimeAmdf computes the lag of the average magnitude difference function
PitchTimeZeroCrossings computes f_0 through zero crossing distances
SOURCE CODE
%blocks audio signal into overlapping blocks
%>
%> @param x: audio signal (dimension length x 1)
%> @param iBlockLength: target block size
%> @param iHopLength: target hopsize
%> @param f_s: sample rate
%>
%> @retval x_b (dimension iNumOfBlocks x iBlockLength)
%> @retval t time stamps for blocks
% ======================================================================
function [x_b, t] = ToolBlockAudio(x, iBlockLength, iHopLength, f_s)
    iNumBlocks = ceil(size(x, 1)/iHopLength );
    % time stamp vector
    t = (0:(iNumBlocks-1)) * iHopLength / f_s + iBlockLength/(2*f_s);
    % pad with zeros just to make sure it runs for weird inputs, too
    xPadded = [x; zeros(iBlockLength+iHopLength, 1)];
    x_b = zeros(iNumBlocks, iBlockLength);
    for n = 1:iNumBlocks
        x_b(n, :) = xPadded((n-1)*iHopLength+1:(n-1)*iHopLength+iBlockLength);
    end
end