Description of ToolDownmix
Home > ACA-Code > ToolDownmix.m
ToolDownmix
PURPOSE
downmixes audio signal
SYNOPSIS
function [x_downmix] = ToolDownmix(x)
DESCRIPTION
downmixes audio signal
>
> @param x: audio signal (dimension length x channels)
>
> @retval x_downmix (dimension length x 1)
 ======================================================================
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ComputeBeatHisto computes a simple beat histogram
ComputeFeature computes a feature from the audio data
ComputeFingerprint computes a fingerprint of the audio data (only the subfingerprint, one
ComputeMelSpectrogram computes a mel spectrogram from the audio data
ComputeNoveltyFunction computes the novelty function for onset detection
ComputePitch computes the fundamental frequency of the (monophonic) audio
ComputeSpectrogram computes a mel spectrogram from the audio data
SOURCE CODE
%downmixes audio signal
%>
%> @param x: audio signal (dimension length x channels)
%>
%> @retval x_downmix (dimension length x 1)
% ======================================================================
function [x_downmix] = ToolDownmix(x)
    if (size(x, 2) > 1)
        x_downmix = mean(x, 2);
    else
        x_downmix = x;
    end
end